# Generated by Django 5.2.6 on 2025-10-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
