# Generated by Django 5.2.6 on 2025-10-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroSabor', models.CharField(max_length=200)),
                ('segundoSabor', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('borda', models.CharField(max_length=200)),
                ('precoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaria.pizzaria')),
            ],
        ),
    ]
